mwclient/page.py
Those values are only accessible through the private dict _info. Making them available directly may be useful to mwclient users.
=> Adding pageid, contentmodel, pagelanguage, restrictiontypes as attributes of Page

mwclient/page.py, tests/test_page.py
Store the results of page.text() operations in a simple cache dict. This avoids unnecessary remote roundtrips. Cache is cleared on each successful page save operation; we might want to also have a method to clear the cache, TTL, whatever, if folks are likely to keep Page instances around a long time and need to refresh them for possible third party edits.
This also gets rid of the section attribute, which looks bogus to me. All it appears to achieve is that if you retrieve the text of a particular section, then run a 'save' operation without explicitly specifying a section, the save operation is applied to the same section. This seems a completely wrong and potentially dangerous assumption. Maybe I'm missing something, though.
This is a pretty simple-minded implementation I wouldn't …
=> cache page text until next edit operation

mwclient/client.py, mwclient/page.py
A long while ago, I got a request from @waldyrious to integrate [changes I had made in my clone of mwclient](https://bitbucket.org/rdhyee/mwclient/branch/wpp?dest=r97#chg-mwclient/page.py) into this repo. (Sorry to take so long!)   The basic change I had made was to add a `revisions` method to the `Site` object and modify the source so that I can make use of the `rvdiffto` parameter for [prop=revisions](https://en.wikipedia.org/w/api.php?action=help&modules=query%2Brevisions)
This PR is a naive integration of the code I wrote (which was based off of the 0.6.5 or r97 versions of mwclient.) I know a significant amount of the library has changed.  I welcome:
* feedback on whether this code is useful
* how to clean up this PR so as to conform to the latest structure of mwclient.
=> including a function to return revisions and allow for diffto

mwclient/listing.py
Credit for this fix goes to @tosher:
https://github.com/mwclient/mwclient/issues#issuecomment-154751657
I just figured out exactly what changes his comment suggested,
and poked around a bit to figure out what was going on and why
they're needed.
`GeneratorList` (and things deriving from it, e.g. `Category`)
was broken for iteration purposes in Python 3. In Python 3
the iterator protocol requires a `__next__` method, not a `next`
method as in Python 2. 8d0650c renamed `List`'s `next` method
to `__next__` and added a small wrapper `next` method to account
for this, but did not make the same change for `GeneratorList`.
So when you iterate over a `GeneratorList` with Python 3, it
winds up calling `List.__next__` (since `GeneratorList` inherits
from `List`), not `GeneratorList.next`. So we …
=> [#106] fix GeneratorList with Python 3 (add __next__)

mwclient/ex.py
per https://docs.python.org/2/reference/simple_stmts.html ,
as exec is a function not a statement in py3, the py2 version
has been set to allow the subsequent statement to be a tuple,
so we can invoke it like this to make it both py2 and py3
compatible. Without this, byte-compiling the file fails under
py3.
Disclaimer: I have no clue if this does the right thing or if `ex.py` works or does anything at all, with or without this change. I just know it stops my Fedora package build complaining. :)
=> use 'exec' in py3-compatible manner

mwclient/listing.py
this is sometimes useful; for instance I have a use case for
getting all pages in a given namespace that are alphabetically
between two specific points (because their names are in a
predictable format that involves alphabetically-sorted dates).
'end' is added as the last kwarg to avoid breaking any current
uses that rely on the kwarg ordering (thanks dan for pointing
that out).
=> add 'end' arg for PageList

mwclient/client.py
* Possibility to turn off ssl certificate validation (for self-signed certs on corp. wikies)
* Proxy connection support.
=> Possibility to turn off ssl certificate validation and proxy connection

mwclient/client.py
Beaware argument requests from the constructor has been rename reqs
=> Rename constructor arg requests to reqs to Fix #118

examples/basic_edit.py, examples/upload.py
This clears errors detected by landscape.io:
https://landscape.io/github/mwclient/mwclient/35/messages/error
Fixes based on recommendations here: http://python-future.org/compatible_idioms.html
=> make examples python-3 compatible

mwclient/client.py
this follows on from #114 and addresses #87, providing an `end`
arg for all these generators, letting you get 'all pages between
Bar and Foo' or whatever it is you may need.
Untested, I just followed how the 'start' stuff works now.
=> add 'end' argument for `allpages`, `allusers` etc. generators

README.rst
otherwise the logo gets awkwardly separated from the title
=> move badges to under the main heading

mwclient/client.py, tests/test_client.py
Allow sending custom headers (e.g. X-Wikimedia-Debug) with all requests
by passing a dict of header data in the Site constructor.
=> Support sending custom headers with all requests

examples/basic_edit.py, examples/upload.py
Examples should adhere to PEP-8 guidelines, as these examples
not only document how to use correctly the client, but also
will serve as a first exposition to Python for some contributors.
Reference: https://www.python.org/dev/peps/pep-0008/
=> Improve PEP-8 compatibility for examples

mwclient/client.py
In 1d61770 the Site.parse() command was changed from GET to POST. This
effectively limits the amount of wikitext that can be rendered to what
will fit in the URI limit of the webserver serving the MediaWiki site.
We could do something really tricky to look at the size of the text
argument and switch between GET and POST based on that, but it seems
much simpler to just stick with POST for this action.
Downstream bug: https://phabricator.wikimedia.org/T158715
=> Send parse requests via POST

mwclient/client.py, tests/test_client.py
Did some rebasing of #155, but since the pull request was from the master branch I couldn't overwrite it, so I created a new PR.
Note that I modified the `get_token()` method to use `raw_api()`, so that it can be used in the `login()` method. Also fixed the tests.
Can you give it a test, @ubibene ?
I created a separate issue for the session timeout problem, #158 .
=> Fix semantic mediawiki call and login with MW > 1.27 , Issue #153 and Issue #149

mwclient/client.py
retry on redis/memcached connection error, which looks like a nonce reuse
https://phabricator.wikimedia.org/T106066
indicates that while the text of the error message is perhaps poor (in that it should propagate or better communicate the upstream error from memcached or redis), but that fundamentally this is not something that the mediawiki folks seem inclined to change on the server side.
https://phabricator.wikimedia.org/T109173
indicates that the error is well known to the pywikibot code, and that they've addressed it via
https://gerrit.wikimedia.org/r/#/c/289582/
=> detect, warn and retry on nonce error

mwclient/client.py
This allows the order of JSON results returned by the api to be preserved. This is important at least for the SMW api, where you can provide ordering criteria in your query. See #170.
=> using OrderedDict as object_pairs_hook (#170)

README.rst
See https://github.com/github/markup/issues/556 for more details.
The rendering is [not entirely correct](https://github.com/github/markup/issues/556#issuecomment-326223588), so don't merge yet, but it [should work soon](https://github.com/github/markup/issues/556#issuecomment-326466252).
=> README: use SVG version of the logo

setup.py, tests/test_client.py
This reverts commit 1650e0e77d370ff5d7b089b60353854d548fb0a1.
Upstream restored handling of the adding_headers arg in 0.6.1.
Going back to using that name means we're still compatible with
any version of responses after 0.3.0, except 0.6.0. Also adjust
setup.py to express this correctly.
=> Revert "Fix test compat with responses@0.6.0"

mwclient/client.py, mwclient/util.py
Use chunked file uploading for files larger than 1 MB as long as we’re on MediaWiki >= 1.20.
Any issues you can think of with this?
=> [#189] Add chunked file uploads

docs/source/user/connecting.rst, docs/source/user/page-ops.rst
This is what is imported at the beginning of the examples.
This could also be done by changing the import to 'import mwclient'
rather than 'from mwclient import Site'.
Neither seems more correct but I have tried to follow
what seems most intended.
>>> from mwclient import Site
>>> site = mwclient.Site('en.wikipedia.org')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
NameError: name 'mwclient' is not defined
vs.
>>> site = Site('en.wikipedia.org')
>>> page = site.pages['Greater guinea pig']
>>> text = page.text()
>>> page.exists
True
=> Change invocation syntax to relative Site() in examples

.travis.yml, mwclient/__init__.py, mwclient/client.py, mwclient/errors.py, setup.cfg, setup.py, tox.ini
pep8 has been replaced with codestyle.
pytest-cache is now included in pytest.
=> Pycodestyle

mwclient/util.py, test/test_util.py
New pull request since I couldn't reopen #216
=> Make util.parse_timestamp() always return a time.struct_time() object.

docs/source/development/index.rst
We switched to pycodestyle then flake8 recently, but one stray
reference to pep8 was left in this doc file.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> Remove one more stray reference to pep8

tox.ini
The `commands` line was accidentally(?) removed entirely in
57f716e, so tox no longer actually ran any tests (only flake8).
This restores it, with the codestyle bit removed obviously. It
also fixes two lines where a tab was used instead of spaces.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> tox.ini: restore commands line, fix tabs vs. spaces (#224)

docs/source/user/connecting.rst, mwclient/client.py
Use and recommend format from RFC 7231.
Give examples for custom User-Agent strings.
Closes #49
=> Improve User-Agent and documentation

mwclient/client.py
Add a parameter named `scheme` to the constructor of the `Site` class which allows to specify the URL scheme used. It defaults to *https* (thus not changing the current default behaviour) but it can also be set to *http* to allow access to unencrypted sites.
This fixes #212
=> Allow URL scheme to be configured in a more intuitive way

mwclient/client.py, test/test_client.py
I don't really understand why the `ask()` method yields key-value pairs (`yield {key: value}`) rather than just the values (`yield value`). Since they are yielded from a generator, the keys cannot be used for indexing, so I wonder if this was just a mistake, and I'm tempted to simplify it to yield just the values (result objects), but this will be a breaking change. Do you have any opinions on this, @ubibene ?
As I was querying a site with SMW 2.3.0 I also learned that the format of the results changed either in SMW 2.4.0 or 2.5.0, so I'm adding a check to support both the old format and the new.
=> BC: Simplify SMW ask output structure

mwclient/client.py, mwclient/page.py, test/test_page.py
Allow specifying `uselang` with `Page.revisions()` and `Site.usercontributions()` to get localized parsed comments with `prop=parsedcomment`.
Do we need to support `uselang` more places? I don't see a big point in localized error messages, but there could be other uses.
=> Add uselang to revisions() and usercontributions()

.editorconfig
- Set the top level `.editorconfig` file as the root (good practice).
A bunch of rules to match the existing conditions:
- Indent `.cfg`, as well as `Makefile`s using tabs instead of spaces.
- Set an indent-size of 2 instead of 4 for `.yml` and `.yaml` files.
- Set a max line length of **90** (non standard) for Python files, as this seems to best match the existing code-base, though some changes will be necessary to make it fully compliant. Alternatively I'd like to suggest a max line length of either 79 (pep8) or just going up to something like 100 or even 120 characters.
=> Expanding the .editorconfig file

docs/source/index.rst, docs/source/user/connecting.rst
This fixes the warning:
```
DeprecationWarning: Specifying host as a tuple is deprecated as of mwclient 0.10.0. Please use the new scheme argument instead.
=> doc: Update index.rst

.gitignore, docs/source/user/page-ops.rst, examples/basic_edit.py, mwclient/errors.py, mwclient/page.py, test/test_page.py
Add support for using appendtext or prependtext instead of text in an api edit request. This also allows a graceful way to blank/null edit a page without having to spend two api queries to get the text and then save, so add page.touch() as well using this.
=> Add append/prepend setting in save & use this to add touch

README.md, tox.ini
Support for Python 3.4 is stated in multiple places and already tested by the tox.ini
=> remove: py34 references

docs/source/user/connecting.rst, docs/source/user/files.rst, docs/source/user/implementation-notes.rst, docs/source/user/page-ops.rst
- Improve anchors in user/connecting.rst
- Move the auth anchor to be above the correct section
- Add missing anchors so all sections have them
- Add blank line above the old_login anchor and use hyphen instead of _.
- Remove backticks in anchor names, for consistency
=> Docs: Improve anchors in user/connecting.rst

mwclient/client.py, test/test_client.py, test/test_listing.py, test/test_page.py
This library currently uses `simplejson` instead of `json` conditionally in multiple places. Presumably, this was done for compatibility with Python versions prior to 2.6, when `json` was added to the standard library. As this library only supports 2.7+, this should not be needed anymore.
=> remove: simplejson dependency

mwclient/__init__.py
Not required as `logging.NullHandler` is available on all supported python versions. See [here](https://docs.python.org/2/library/logging.handlers.html#nullhandler) and [here](https://docs.python.org/3/library/logging.handlers.html#nullhandler).
=> remove custom null handler

mwclient/client.py, test/test_client.py
From [the doc](https://www.mediawiki.org/wiki/API:Login)
> As of MediaWiki 1.27, using the main account for login is not supported. Obtain credentials via Special:BotPasswords or use clientlogin method.
MediaWiki 1.34 `login` method is still working with normal account but "raises Deprecated" (send content into "warnings"). This PR adds support of clientlogin to avoid those warnings and prepare to future versions when `login` method will only work with "Bot passwords"
=> Add support for clientlogin

tox.ini
This is a missing bit of the CI enablement, per
https://github.com/ymyzk/tox-gh-actions . I hope this will make the Python 3.6 tests run properly.
Signed-off-by: Adam Williamson <awilliam@redhat.com>
=> Add gh-actions section to tox.ini

docs/source/user/connecting.rst
Resolves #262 by documenting how to connect to MediaWiki instances using a proxy.
=> Document how to connect using a proxy

mwclient/page.py, test/test_page.py
Issue #290 gives an example of a wiki with protected pages whose protection definitions have no 'expiry' key at all. This seems strange and, on a quick through the mediawiki code, difficult to achieve, but since there's a live site out there that does it, and mediawiki *does* seem to have at least some code to handle such cases (e.g. how the expiry shows as 'indefinite' in the page information), let's handle it too, by representing this as None.
=> Handle page protection having no expiry (#290)

mwclient/client.py
Resolves #240 by documenting how to retrieve the entire block log for a given user.
=>  #240: Add reference to Site.logevents in the Site.blocks docstring

setup.py, tox.ini
test_client.py uses pkg_resources. That's part of setuptools, not Python. Per
https://docs.python.org/3.12/whatsnew/3.12.html#removed , it was previously included by default in venv environments, but no longer is from 3.12 onwards, so we need to explicitly require setuptools to ensure it's available.
=> Mark tests as requiring setuptools in tox.ini and setup.py

docs/source/index.rst, docs/source/user/connecting.rst, docs/source/user/page-ops.rst
Improve the documentation in response to #302 by adding a new warning to the documentation more clearly recommending users to set a User-Agent.
This also updates the initial examples on the "Connecting to your site", "Page operations", as well as "Quickstart" pages with a User-Agent.
=> Update docs to recomment setting a user-agent

.readthedocs.yaml, docs/requirements.txt
Read the Docs has started requiring a .readthedocs.yaml configuration file to be present in the repository in order to build the documentation.
https://blog.readthedocs.com/migrate-configuration-v2/
According to the timeline we have until 2023-09-25 to migrate to the new configuration file, but we've already had some builds fail during their 48-hour brownout on 2023-09-04.
=> Add .readthedocs.yaml configuration file

mwclient/client.py, mwclient/image.py, mwclient/listing.py, mwclient/page.py
=> Fix inheritance issue in __repr__() methods

.github/workflows/tox.yml
I think we can just do this now Python 3.12 is stable.
=> Update GHA config for Python 3.12 final

mwclient/client.py, test/test_client.py
As discussed upstream in
https://github.com/psf/requests/issues/4564 , HTTP basic auth usernames and passwords sent to requests as Python text strings are encoded as latin1. This of course makes it impossible to log in with a username or password containing characters not represented in latin1, as the reporter of #315 found out.
To work around this rather old-fashioned default, let's intercept string usernames and passwords and encode them as utf-8 before sending them to requests.
Anyone dealing with a really old server that can't handle utf-8, or something like that, can encode the username and password appropriately and provide them as bytestrings.
=> HTTP basic auth: encode username and password as UTF-8 (#315)

mwclient/client.py, mwclient/listing.py, mwclient/page.py, setup.py, test/test_client.py, test/test_listing.py, test/test_page.py, test/test_sleep.py, test/test_util.py
* `Iterator.next()` has been replaced with `Iterator.__next__()`
* The `object.__unicode__()` method is not used anymore
* Default source encoding has changed from ASCII to UTF-8
=> Remove some Python 2.x leftovers

.github/workflows/docs.yml
Use [readthedocs/actions/preview](https://github.com/readthedocs/actions/tree/v1/preview) to add links to ReadTheDocs to pull requests.
=> Add ReadTheDocs links to pull requests

.github/workflows/tox.yml
This was lost when Travis stopped working, so our coveralls data is frozen in 2021. This should get it working again using https://github.com/marketplace/actions/coveralls-github-action if I got it right.
=> Use Coveralls Github Action to send data to coveralls again

README.md
This adds a paragraph covering former and current mwclient maintainers. It also fixes the build status badge to come from Github Actions, since we no longer use Travis.
=> README updates: credit authors/maintainers, update build status badge

.github/workflows/tox.yml, tox.ini
Adds the Python 3.13.0-alpha to Tox and the GitHub action.
=> Add Python 3.13-alpha to Tox/GHA

.github/workflows/release.yml, .gitignore, docs/source/development/index.rst, pyproject.toml, setup.cfg, setup.py
This adds a release workflow, and updates tool config a bit to make the latest incarnation of bumpversion happy. I've tested that you can do `bump-my-version bump major` on top of this and it looks like it does everything we'd want - update all the appropriate version strings and create a tagged commit. So I *hope* that, once we merge this, we can submit another PR created by editing `CHANGELOG.md` then running `bump-my-version bump major`, then merge that PR and the release should happen magically.
=> Add an automated release workflow using Github Actions

docs/source/user/connecting.rst
Attempt to resolve #322, by clarifying the authentication section of the documentation.
=> Update authentication method docs

docs/source/user/connecting.rst
I tried to make this as accurate as possible based on the method docstrings and the upstream docs.
=> Document the clientlogin method, mark login as deprecated

MANIFEST.in
The tarballs from current releases have these files in them, but building with `build` does not include them. I don't know if the previous maintainer was using setuptools-scm or something like that, but this should ensure that appropriate files are included in our new tarballs. I left out things like .gitattributes which clearly shouldn't be in a release tarball.
=> Add several things to MANIFEST.in that are in current tarballs

.github/workflows/release.yml
This is the one from
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ again, with an `if` condition added and multilines rewrapped. As best as I can tell, this should work automagically, we don't need to "sign up for" sigstore or create any certificates or keys; it works by creating an ephemeral signing certificate bound to the identity of whatever GitHub user the workflow runs as (proved by OIDC), and signing with that.
=> Add a sign/GH release job to the release workflow

docs/source/user/connecting.rst, mwclient/client.py, test/test_client.py
As discussed in #197, this renames the `reqs` argument to `Site` to `connection_options`. The old name still works but triggers a DeprecationWarning. If you specify both we raise ValueError.
=> rename `reqs` arg to `connection_options` (#197)

mwclient/client.py, mwclient/errors.py, test/test_client.py
Fixes #211 by raising an error when `ignore=False` and the MediaWiki response contains the `upload.warnings.exists` key. Previously, this warning was logged, but the call to `Site.upload` succeeded. This could be easily missed by users, especially when they haven't configured the log level.
=> Implement error handling for MediaWiki warnings on existing files

docs/source/user/implementation-notes.rst, mwclient/client.py, mwclient/image.py, mwclient/listing.py, mwclient/page.py, mwclient/util.py, test/test_listing.py
As discussed in #259, the `limit` parameter - to the low-level `listing.List` and its subclasses, and to various higher-level functions which ultimately return `List` or `GeneratorList` instances - is confusing and misleading.
It is passed through to the API calls, and effectively specifies how many items a single API call will return. But because our `List` yields a single item at a time and will keep doing API calls until the API says there's no more data, it does not limit how many items our `List` will yield, nor specify its chunk size. It seems natural to expect that `List(limit=10)` or `page.revisions(limit=10)` will give you a generator that yields only 10 items, or yields 10 items at a time, but it does not; it gives you a generator which queries the API in chunks of 10 items at a …
=> Deprecate `limit` for `api_chunk_size`, extend `max_items` (#259)

README.md, mwclient/client.py, pyproject.toml, setup.py
This has the commit for the 0.11.0 release, plus a preparatory tweak to pyproduct.md. After merging this I need to figure out how to get the tag pushed, then the release should happen.
=> 0.11.0 release prep

mwclient/client.py
I found this while writing integration tests. If you try to login with an incorrect username and password, mwclient correctly raises mwclient.errors.LoginError...but if you then check logged_in, it is True. Clearly that's wrong.
The logic for setting logged_in will basically consider us logged in any time we process an API call and there is no 'anon' key in the userinfo dict *or there is no userinfo dict at all*. The last API call processed on a failed login attempt has no userinfo dict.
This tweaks it so we only changed the logged_in value (in either direction) if the API call we're handling has a userinfo dict.
We also fix the type of the empty userinfo we create if there isn't one in the call (no idea why it was a tuple, it doesn't really matter but it's weird) and explicitly set …
=> Make logged_in more accurate

.github/workflows/integration.yml, .github/workflows/tox.yml, docs/source/development/index.rst, pyproject.toml, test/integration.py, tox.ini
This adds an integration test that runs a mediawiki container, configures it enough that the API works, then runs a single test against it. We also enable this in CI, if I got it right. WIP!
=> Initial container-based integration testing

mwclient/client.py
This prevents the program from straight-up failing, instead resorting to retries if they are enabled.
=> Made 429 Too Many Request HTTP error in `raw_call()` of `client.py` retryable

README.md, mwclient/client.py, mwclient/listing.py, test/test_listing.py
These commits together get listing.py test coverage up to 100%. They include a couple of functional changes where I think it makes more sense to change the code than change the tests. Particularly notably, it would bump our baseline version of mediawiki to 1.26, which was released in 2015 and has been obsolete since 2016. We could do some follow-up commits to drop conditionals for older releases, if we agree this bump is reasonable.
=> 100% test coverage for listing.py

mwclient/client.py, test/test_client.py
[In the MediaWiki documentation](https://www.mediawiki.org/wiki/Manual:$wgVersion#Example_code), versions are compared using [PHP's version_compare](https://www.php.net/manual/de/function.version-compare.php) function, which canonicalizes version strings by:
- Replacing _, -, and + with dots (.)
- Inserting dots before and after any non-numeric characters
The version string is then split on the dots, and the resulting segments are compared from left to right. This PR updates `Site.version_tuple_from_generator` to parse versions according to those rules.
Additionally, this PR:
- Adds a new check to `version_tuple_from_generator` to make sure that the first two elements in the resulting version tuple are always integers.
- Makes sure we consistently use `Site.require` instead of comparing …
=> Update version_tuple_from_generator to match PHPs' rules

README.md, docs/source/index.rst, docs/source/reference/errors.rst, mwclient/errors.py, mwclient/image.py, mwclient/listing.py, mwclient/page.py
This PR contains various improvements to the documentation (see individual commits).
* Adds documentation to the `Page`, `Image`, and `Category` constructors.
* Adds all errors to the documentation. Previously only `mwclient.errors.InsufficientPermission` was included.
* Update the required Python/MediaWiki versions in the docs.
* Add information about the version scheme/license
=> Various documentation updates

.gitignore, docs/source/conf.py, examples/upload.py, mwclient/__init__.py, mwclient/client.py, mwclient/errors.py, mwclient/image.py, mwclient/listing.py, mwclient/page.py, mwclient/sleep.py, mwclient/types.py, mwclient/util.py, pyproject.toml, test/integration.py, test/test_client.py, test/test_listing.py, test/test_page.py, tox.ini
Since dropping Python 2 support in #310, we now have the ability to add type annotations to the codebase. I think this could be very helpful for users to discover the API and to prevent bugs.
This PR is intended as a starting point for discussions (@mwclient/maintainers) and adds basic type annotations to all functions. Since we often return responses from the MediaWiki API verbatim, I've chosen to leave the return type as `Any` or `Dict[str, Any]` in many cases. This could be improved, for example, with `TypedDict`s, but I'm not sure we want to take on that maintenance burden.
Here are some open questions I have regarding this:
1. Do we want to maintain types in the first place?
2. Which type-checker should we use? I've chosen mypy for now, but we could, for example, use pyright instead. …
=> Add Type Annotations to the Codebase

mwclient/listing.py, test/test_listing.py
The previous type-annotation was too narrow here (and even required a `type: ignore[index]`). `PageList.get` also works with `int` and `Page` objects.
=> Allow passing `int` and `Page` objects to `PageList.get` and `__getitem__`

mwclient/listing.py, mwclient/page.py, test/test_page.py
As discussed in #354, this change updates the page attributes without extra API calls after each (successful) call to `Page._edit` and its upstream functions (`Page.save`, `Page.edit`, `Page.append`, `Page.prepend`, and `Page.touch`). This is more or less what I suggested in [this comment](https://github.com/mwclient/mwclient/issues/354#issuecomment-2317762162).
@AdamWill [you mentioned](https://github.com/mwclient/mwclient/issues/354#issuecomment-2318077642) having an alternative patch lying around. I've checked the "Allow edits and access to secrets by maintainers" option, so you should be able to push to this branch if you have any changes/improvements over this.
resolves #354, resolves #63
=> Update page attributes after edit

.github/workflows/tox.yml
ubuntu-latest is in the process of being updated from ubuntu-22.04 to ubuntu-24.04, which leads to issues with py37:
```
Version 3.7 was not found in the local cache
Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
```
This commit hard-codes the ubuntu-version for py37 to ubuntu-22.04, similar to what we've done for py36.
See actions/runner-images#10636 for more information.
=> Hard-code ubuntu-22.04 for Python 3.7 CI jobs

.github/workflows/integration.yml, .github/workflows/tox.yml, pyproject.toml, tox.ini
This PR adds the `Programming Language :: Python :: 3.13` classifier to `setup.py`. It also updates the Python version used for running tests, linting, and mypy to 3.13, and adds Python 3.14.0-alpha to the Tox configuration. 
We should wait until actions/python-versions#312 is merged before proceeding with this PR, as the CI will fail until then.
=> Add Python 3.13 classifier and start testing with 3.14-alpha

pyproject.toml
These options were removed in 96dea32 but were unintentionally reintroduced in #360 as part of 859f3ee. This can cause issues in certain CI environments (see #340). Additionally, the module name after `--cov` is incorrect, resulting in the following warning:
```
CoverageWarning: Module mwtp was never imported. (module-not-imported)
self.warn(f"Module {pkg} was never imported.", slug="module-not-imported")
```
=> test: remove pytest.ini_options from pyproject.toml

.readthedocs.yaml, docs/requirements.txt, docs/source/development/index.rst, pyproject.toml
This PR moves the dependencies required to build the docs from `docs/requirements.txt` to the `pyproject.toml` and updated the build os/python version.
It also updates the "Updating/expanding the documentation" section of the documentation with the new build commands and adds some more information.
=> Update documentation config and dependencies

mwclient/client.py, test/integration.py, test/test_client.py
Refactored `Site.expandtemplates` to use the updated API, addressing deprecation warnings in recent MediaWiki versions.
The older API triggered the following warnings:
```
WARNING:mwclient.client:Subscribe to the mediawiki-api-announce mailing list at <https://lists.wikimedia.org/postorius/lists/mediawiki-api-announce.lists.wikimedia.org/> for notice of API deprecations and breaking changes. Use [[Special:ApiFeatureUsage]] to see usage of deprecated features by your application.
WARNING:mwclient.client:The parameter "generatexml" has been deprecated.
Because "prop" was not specified, a legacy format has been used for the output. This format is deprecated, and in the future the new format will always be used.
```
=> Update `Site.expandtemplates` to use the new API added in 1.24

mwclient/client.py
Adds some documentation to explain why certain methods take both `*args` and `**kwargs` instead of just `**kwargs`. See #128 for more information.
=> docs: document why some functions accept both `*args` and `**kwargs`

mwclient/client.py
Hi
According to the API documentation for MediaWiki we still seem to need the `createaccount`-tokens to add user accounts to the wiki: https://www.mediawiki.org/wiki/API:Account_creation#Python.
Could you whitelist the `createaccount` token requests, please?
Regards,
Oliver
=> Please whitelist requesting createaccount tokens in get_token

.github/workflows/integration.yml, .github/workflows/release.yml, .github/workflows/tox.yml
This PR pins all third-party GitHub Actions to specific commit hashes. This helps prevent supply chain attacks, like CVE-2025-30066, where a tag is updated with malicious code. Dependabot will still create PRs for new versions, but that at least gives us a chance to review changes before merging.
=> ci: pin third-party GitHub Actions to commit hashes

.github/workflows/tox.yml, README.md, docs/source/index.rst, pyproject.toml, tox.ini
GitHub has deprecated the `ubuntu-20.04` runner, which was the last image supporting Python 3.6: https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
Additionally, actions/setup-python will not be updated to support Python 3.6 going forward: actions/setup-python#1048
As a result, Python 3.6 is no longer easily testable and I've removed it from the matrix.
@mwclient/maintainers we should decide whether to drop support for Python 3.6 entirely (given that it's EOL for 3+ years), or at least update the documentation to mention that it's not tested in CI and only supported on a best-effort basis.
=> Drop Python 3.6 Support; Require Python >=3.7

mwclient/client.py
We recently had a bug where we weren't sending our custom User-Agent to the WMF servers. The source of this bug was the fact that we were using the `pool` parameter in the `Site` constructor, and therefore `clients_useragent` was being silently ignored.
In lieu of issuing warnings or throwing errors in this situation, this PR simply updates the docs so that future users will have a better chance of figuring out this situation without needing to read the code directly.
=> Update documentation for the Site constructor `pool` parameter
